#!/usr/bin/env bash

killall -q polybar

while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done
# polybar example
polybar left -c $(dirname $0)/config &
polybar center -c $(dirname $0)/config &
polybar right -c $(dirname $0)/config &
